# Configuration Doctrine ORM
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        types:
            tenant_id: Spark\Infrastructure\Persistence\Doctrine\Type\TenantIdType
        
    orm:
        entity_managers:
            default:
                mappings:
                    App:
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'Spark\Domain'
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false