#!/bin/bash

source install-lib/load-env.sh

PROFILE="prod"

function main() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help)
                _show_help
                shift
                ;;
            --profile)
                if [[ "$2" == "devlocal" || "$2" == "prod" ]]; then
                    PROFILE="$2"
                else
                    echo "Erreur: Valeur de --profile invalide. Utilisez 'devlocal' ou 'prod'."
                    exit 1
                fi
                shift 2
                ;;
            *)
                echo "Erreur: Option inconnue $1"
                exit 1
                ;;
        esac
    done
    _run_steps
}

function _show_help() {
    echo "Usage: ./build [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --help        Affiche cette aide"
    echo "  --profile     Définit le profil de build (valeurs possibles: devlocal, prod)"
    echo "                Valeur par défaut: prod"
    exit 0
}

function _run_steps() {
    echo "-------------Step 1: Load env and Create some directories----------------------------------------"
    load_env
    create_usual_directories
    create_data_directory "$DATA_PATH_STORE"
    create_data_directory "$DATA_PATH"
    echo "-------------Step 1: Done!"

    echo "-------------Step 2: Build docker images---------------------------------------------------------"
    init_docker_userid_groupid
    build_docker_images
    echo "-------------Step 2: Done!"

    echo "-------------Step 3: Assure that no docker container is running anymore--------------------------"
    ./stop
    echo "-------------Step 3: Done!"

    echo "-------------Step 4: Build for profile devlocal---------------"
    if [[ "$BUILD_WHEN_INSTALL" = true ]]; then
        ./build --profile devlocal
    fi
    echo "-------------Step 4: Done!"

    echo "-------------Step 5: create database schema if not done---------------"
    create_database_schema_if_no_database_exist
    echo "-------------Step 5: Done!"

    echo "-------------Step 6: create demo tenant---------------"
    # delete demo tenant if exists
    DEMO_TENANT_DIR=$DATA_PATH_STORE/tenants/demo
    if [ -d "$DEMO_TENANT_DIR" ]; then
        rm -Rf $DEMO_TENANT_DIR
    fi

    bin/console tenant:database:create --tenant_id demo
    bin/console tenant:schema:create --tenant_id demo
    echo "-------------Step 6: Done!"
}

function init_docker_userid_groupid() {
    USERID=$(id -u)
    export USERID
    GROUPID=$(id -g)
    export GROUPID
}

function create_usual_directories() {
    if [ -d "./var" ]; then
        rm -Rf ./var
    fi;
    mkdir --parents ./var
    mkdir --parents ./vendor
}

function create_data_directory() {
    DATA_DIR=$1
    echo "DATA_DIR=${DATA_DIR}"
    if [ ! -d "$DATA_DIR" ]; then
        mkdir --parents $DATA_DIR
    fi
    mkdir --parents $DATA_DIR/database
}

function build_docker_images() {
    USERID=$(id -u)
    export USERID
    GROUPID=$(id -g)
    export GROUPID

    docker compose $DOCKER_COMPOSE_FILES build

}

function create_database_schema_if_no_database_exist() {
    echo "Creating database..."
    echo "DATA_DIR=${DATA_DIR}"
    mkdir --parents $DATA_DIR

    SQLITE_FILE=$DATA_PATH_STORE/database/spark.sqlite
    echo "SQLITE_FILE=${SQLITE_FILE}"
    if [ "$REMOVE_DATABASE_WHEN_INSTALL" == true ] && [ -f "$SQLITE_FILE" ]; then
        if [ -f "$SQLITE_FILE" ]; then
            echo "Le fichier $SQLITE_FILE déjà!"
            echo "je le supprime."
            rm "$SQLITE_FILE"
        fi;
    fi;

    bin/console doctrine:schema:create
    echo "Database schema created!"
}

main "$@"
